version: '2'
services:
    forum-app:
        image: forum
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://forum-postgresql:5432/forum
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    forum-postgresql:
        extends:
            file: postgresql.yml
            service: forum-postgresql
